### PR TITLE
Add TextButton and TextMessage components

### PR DESCRIPTION
**Pull request by PaulLeCam**

### CODE REVIEW

**Comment by howleysv** [comment]
@sylane Has all of this been incorporated?

**Comment by sylane** [comment]
It is added to the server validation, if it is what you meant.

**Comment by howleysv** [comment]
@PaulLeCam Will the micro messages be a separate PR?

**Comment by PaulLeCam** [comment]
According to our MEP the server should set the message type as `MICRO` when the `TextMessage` root is used, I think it's more of an implementation detail on our side.

**Comment by howleysv** [comment]
I think we said the bot dev would set a param when sending a message

**Comment by howleysv** [comment]
@sylane Can you update the docs for `/send_message` if this is the case?

**Comment by sylane** [comment]
the `MICRO` type is not tied to the `TextMessage` root... If the message is `MICRO` the root can ONLY be `TextMessage`, and I think that at the moment `TextMessage` may not be allowed for `NATIVE` messages...

**Comment by sylane** [comment]
ok, I'll update the doc...

**Comment by PaulLeCam** [comment]
OK can you document the flag to set in the payload then please according to the server logic?

**Comment by sylane** [comment]
Where should I document this, a new PR ?

**Comment by PaulLeCam** [comment]
Don't hesitate to update in this one if you want

**Comment by PaulLeCam** [comment]
@sylane @howleysv I updated from master, should be good to merge if it looks good to you?

**Pull request merged**
