### PR TITLE
specifying the link preview UI structure

### PR DESCRIPTION
**Pull request by nietaki**

### CODE REVIEW

**Comment by nietaki** [comment]
maybe we should specify some algebraic type like `TopLevelContainer :: Message | Container` and use it in the docs (?)

**Comment by PaulLeCam** [comment]
Should be `Message` only I think for link previews, so the validation applies.

**Comment by PaulLeCam** [comment]
Yes I think it's better to enforce wrapping in a `Message` for now, maybe at some point we could have a `Preview` root if we want to allow different children but from my understanding of preview discussions, for v1 it should be the same.

**Comment by howleysv** [comment]
So does every UI require a `Container` or `Message` root?

**Comment by PaulLeCam** [comment]
When sending a message or link preview -> `Message` root
When displaying a modal -> `Form` if any user input is needed, `List` if only one list needs to be displayed, `Container` for other display-only UIs

**Comment by howleysv** [comment]
Let's add these rules to the docs & validation

**Pull request merged**
